### ISSUE TITLE
GuideDialogFragment does not have a Dialog

### ISSUE THREAD

**Issue by hkercn** [soulqw/Curtain#8]
来自firebase的crash上报：
Fatal Exception: java.lang.IllegalStateException: DialogFragment GuideDialogFragment{32950c} (fc103030-14dd-43f3-8128-980944c99aa7) GuideDialogFragment} does not have a Dialog.
       at androidx.fragment.app.DialogFragment.requireDialog(DialogFragment.java:302)
       at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:425)
       at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at com.soulfa.voicechat.main.MainActivity.onStart(MainActivity.kt:149)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7978)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3512)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7857)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

往抽空更新下，帮忙解决该问题

**Comment by soulqw** [comment]
@hkercn  感觉是你调用这个方法的时候Activity 生命周期状态不太对，你看下是不是使用姿势的问题呢
